# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainFrame.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainFrame(object):
    def setupUi(self, MainFrame):
        MainFrame.setObjectName("MainFrame")
        MainFrame.resize(1920, 1080)
        self.image1_label = QtWidgets.QLabel(MainFrame)
        self.image1_label.setGeometry(QtCore.QRect(100, 450, 400, 400))
        self.image1_label.setStyleSheet("QLabel {\n"
"    border: 1px solid rgb(0, 0, 0);\n"
"}\n"
"")
        self.image1_label.setAlignment(QtCore.Qt.AlignCenter)
        self.image1_label.setObjectName("image1_label")
        self.realtime_label = QtWidgets.QLabel(MainFrame)
        self.realtime_label.setGeometry(QtCore.QRect(550, 350, 801, 651))
        self.realtime_label.setStyleSheet("QLabel {\n"
"    border: 1px solid rgb(0, 0, 0);\n"
"}\n"
"")
        self.realtime_label.setAlignment(QtCore.Qt.AlignCenter)
        self.realtime_label.setObjectName("realtime_label")
        self.start_button = QtWidgets.QPushButton(MainFrame)
        self.start_button.setGeometry(QtCore.QRect(170, 900, 191, 111))
        self.start_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start_button.setStyleSheet("QPushButton {\n"
"    border-image: url(\"button.png\");\n"
"}")
        self.start_button.setText("")
        self.start_button.setObjectName("start_button")
        self.label1 = QtWidgets.QLabel(MainFrame)
        self.label1.setGeometry(QtCore.QRect(1450, 330, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.label2 = QtWidgets.QLabel(MainFrame)
        self.label2.setGeometry(QtCore.QRect(1450, 380, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.class_label = QtWidgets.QLabel(MainFrame)
        self.class_label.setGeometry(QtCore.QRect(1550, 330, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(22)
        self.class_label.setFont(font)
        self.class_label.setObjectName("class_label")
        self.conf_label = QtWidgets.QLabel(MainFrame)
        self.conf_label.setGeometry(QtCore.QRect(1640, 380, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(22)
        self.conf_label.setFont(font)
        self.conf_label.setObjectName("conf_label")
        self.predicted1_label = QtWidgets.QLabel(MainFrame)
        self.predicted1_label.setGeometry(QtCore.QRect(1450, 450, 400, 400))
        self.predicted1_label.setStyleSheet("QLabel {\n"
"    border: 1px solid rgb(0, 0, 0);\n"
"}\n"
"")
        self.predicted1_label.setAlignment(QtCore.Qt.AlignCenter)
        self.predicted1_label.setObjectName("predicted1_label")
        self.status_label = QtWidgets.QLabel(MainFrame)
        self.status_label.setGeometry(QtCore.QRect(140, 350, 311, 81))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.status_label.setFont(font)
        self.status_label.setAlignment(QtCore.Qt.AlignCenter)
        self.status_label.setObjectName("status_label")
        self.time_label = QtWidgets.QLabel(MainFrame)
        self.time_label.setGeometry(QtCore.QRect(1430, 110, 381, 141))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(72)
        font.setBold(True)
        font.setWeight(75)
        self.time_label.setFont(font)
        self.time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.time_label.setObjectName("time_label")
        self.label = QtWidgets.QLabel(MainFrame)
        self.label.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("bg_squid.jpg"))
        self.label.setObjectName("label")
        self.label.raise_()
        self.image1_label.raise_()
        self.realtime_label.raise_()
        self.start_button.raise_()
        self.label1.raise_()
        self.label2.raise_()
        self.class_label.raise_()
        self.conf_label.raise_()
        self.predicted1_label.raise_()
        self.status_label.raise_()
        self.time_label.raise_()

        self.retranslateUi(MainFrame)
        QtCore.QMetaObject.connectSlotsByName(MainFrame)

    def retranslateUi(self, MainFrame):
        _translate = QtCore.QCoreApplication.translate
        MainFrame.setWindowTitle(_translate("MainFrame", "Form"))
        self.image1_label.setText(_translate("MainFrame", "Image1"))
        self.realtime_label.setText(_translate("MainFrame", "real-time"))
        self.label1.setText(_translate("MainFrame", "Class:"))
        self.label2.setText(_translate("MainFrame", "Confidence:"))
        self.class_label.setText(_translate("MainFrame", "Circle"))
        self.conf_label.setText(_translate("MainFrame", "96.84%"))
        self.predicted1_label.setText(_translate("MainFrame", "Image1"))
        self.status_label.setText(_translate("MainFrame", "Waiting ..."))
        self.time_label.setText(_translate("MainFrame", "00:00"))
